#!/bin/bash

function post_pkg_postinst() {
  grep -Fq ' buildpkg ' <<< {$PORTAGE_FEATURES}
  if [ $? -eq 0 ]; then
    # Change this according to your settings.
    # Add your repository taht you want to use as gentoo-binhost, your personal GitHub access token and your email.
    # To proceed, you must generate a GitHub access token with permissions to access the repository and create releases.
    /usr/sbin/gh_deploy.py
  fi
}
